// <auto-generated />
using ApiRestEstudos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiRestEstudos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531152603_SeedLocations")]
    partial class SeedLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiRestEstudos.Api.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Turismo",
                            Latitude = -22.951899999999998,
                            Longitude = -43.210500000000003,
                            Nome = "Cristo Redentor"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Turismo",
                            Latitude = -22.948899999999998,
                            Longitude = -43.157600000000002,
                            Nome = "Pao de Acucar"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Praia",
                            Latitude = -22.9711,
                            Longitude = -43.182299999999998,
                            Nome = "Praia de Copacabana"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Praia",
                            Latitude = -22.986799999999999,
                            Longitude = -43.200600000000001,
                            Nome = "Praia de Ipanema"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Estadio",
                            Latitude = -22.912199999999999,
                            Longitude = -43.230200000000004,
                            Nome = "Maracana"
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Parque",
                            Latitude = -22.966899999999999,
                            Longitude = -43.224299999999999,
                            Nome = "Jardim Botanico"
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "Parque",
                            Latitude = -22.9602,
                            Longitude = -43.210900000000002,
                            Nome = "Parque Lage"
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "Praia",
                            Latitude = -22.9894,
                            Longitude = -43.191699999999997,
                            Nome = "Arpoador"
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Trilha",
                            Latitude = -22.997399999999999,
                            Longitude = -43.2742,
                            Nome = "Pedra da Gavea"
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "Parque",
                            Latitude = -22.9072,
                            Longitude = -43.223100000000002,
                            Nome = "Quinta da Boa Vista"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
